### ISSUE TITLE
Calculation issue with several gym stat awards

### ISSUE THREAD

**Issue by kib** [Kivou-2000607/yata#168]
The awards for the 10 million for strength, dexterity, speed and defense all show a question mark at the end of the line and the tooltip text "You need at least 100,000,000 dexterity for a prediction of the time left"

I think this is the case for all gym honors at the moment. The code in question is here: https://github.com/Kivou-2000607/yata/blob/c34701c5e979f455a3458ac2c226dfa1271141c2/awards/functions.py#L1459

**Comment by Kivou-2000607** [comment]
Yes it's normal. I do a linear interpolation for the days left And the growth is only linear after 50m stats. So the closest merit is 100m.

But there is a big problem with this prediction. If you were above 100m when the honor was released the prediction is crap... because it assumes that you reach 100m when you receive the honor.

That's the best prediction I can do with close to 0 effort ^^

**Comment by kib** [comment]
I understand your explanation. Perhaps rewording the message is a good option.

**Comment by Kivou-2000607** [comment]
07081ed76a50c1823b0694f3fee1eaaa881b2944
