### ISSUE TITLE
Solve some css/style issues

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#362]
- [ ] font awsome icons overlapping title text (on phone)
- [x] header going out of frame for small screens
- [ ] oversized fonts

EDIT: these bugs seem to only affect old versions of chrome for mobile (the one used by kiwi)

Can't reproduce with desktop with:
- Chromium: Version 85.0.4183.121 (Official Build) Arch Linux (64-bit)

**Comment by SVD-NL** [comment]
Issues on mobile: (tested on Kiwi Browser for android, Version: Git201009 unless stated otherwise)

- Icons and text have no spacing, or merge into each other (does not appear on mobile chrome). Perhaps solved by latest update after hard reload? Doesn't seem that way.

- Wrong font size on [https://yata.alwaysdata.net](https://yata.alwaysdata.net) ![Screenshot_20201014-221427~2.png](https://user-images.githubusercontent.com/72652479/96040711-08641b80-0e6b-11eb-942d-420c29d76240.png)

- [https://yata.alwaysdata.net/bazaar/](https://yata.alwaysdata.net/bazaar/) is fine: ![Screenshot_20201014-221944.png](https://user-images.githubusercontent.com/72652479/96040997-701a6680-0e6b-11eb-86e3-f4707baebb2b.png)
_unless_ you expand the tutorial at the bottom, that causes the "tutorial" font size to be larger, and also causes all of the all of the other expandable sections to be the incorrect font size when interacted with.
This is reverted when the "tutorial" section is collapsed again, but elements stay the wrong size unless interacted with.
Best way to explain is that each of the section headers changes to the font size the "tutorial" header has when you interact with them.
![Screenshot_20201014-222537.png](https://user-images.githubusercontent.com/72652479/96041740-97bdfe80-0e6c-11eb-8057-e5d84b691e7d.png)

- [https://yata.alwaysdata.net/bazaar/sets/](https://yata.alwaysdata.net/bazaar/sets/) loads the wrong font size by default, looks the same as the above

- [https://yata.alwaysdata.net/bazaar/all/](https://yata.alwaysdata.net/bazaar/all/) and [https://yata.alwaysdata.net/bazaar/abroad/](https://yata.alwaysdata.net/bazaar/abroad/) load the incorrect font size by default, except for the "tutorial" header. It does change to the incorrect font size when expanding, and does not reset when collapsed here.

Reloading the page does actually load most elements with the right font size. I don't know how much this is influenced by caching, but unless its relevant I won't look into that too much.

- for the above: when the tutorial header has the incorrect size and a new page is loaded within the bazaar section, it is always loaded with the incorrect font size.

- [https://yata.alwaysdata.net/faction/walls/](https://yata.alwaysdata.net/faction/walls/) I don't even know where to start with this one.

- [https://yata.alwaysdata.net/faction/configurations/](https://yata.alwaysdata.net/faction/configurations/) Font size, and toggle to enable/disable key cut off. ![Screenshot_20201014-224514.png](https://user-images.githubusercontent.com/72652479/96043338-16b43680-0e6f-11eb-8e09-997b27c71c10.png)

- [https://yata.alwaysdata.net/faction/armory/](https://yata.alwaysdata.net/faction/armory/) and [https://yata.alwaysdata.net/bot/dashboard/](https://yata.alwaysdata.net/bot/dashboard/)
Are very inconsistent, sometimes they load properly, sometimes they don't, the dashboard can have one server load properly and others not for example. Seems sort of linked to the font size of the previous page?

- [https://yata.alwaysdata.net/awards/](https://yata.alwaysdata.net/awards/) section names cut off. ![Screenshot_20201014-225502.png](https://user-images.githubusercontent.com/72652479/96044166-4e6fae00-0e70-11eb-806b-963b94dfdda3.png)

- On above screenshot you can also see that long text is cut off in tables, this is true site-wide. One of the more annoying examples is the predicted chain end time.

So, uhm, _good luck_ 😜

**Comment by Kivou-2000607** [comment]
Yeah... it works fine with FF now too so yesterday was just a cached css issue.
However I think the old chrome version only shows that there is a bad html syntax in some pages but I cant find it...

I'm not going to change the awards links being cut off. That's how all tables behave in yata. It's cut off if it's too big.
Changing that would mean redesign it for mobile phone. I just don't have the time for that.
